In [1]:
import numpy as np
import pandas as pd
import sklearn
import warnings
warnings.filterwarnings('ignore')

# SLIDE (1) Основы метрик классификации

На вход подаются 2 массива $y_{real}$ - реальные значения бинарных классов и $y_{pred}$ - предсказанные значения бинарных классов. Вам необходимо посчитать, не используя стандартные функции, метрики: 
* $accuracy$
* $precision$
* $recall$
* $F_1$

Возвращать числа нужно именно в данном порядке.

### Sample 1
#### Input:
```python
y_real = np.array([0, 1, 0, 0, 1, 1, 1, 1])
y_pred = np.array([0, 1, 1, 0, 1, 1, 0, 0])
```
#### Output:
```python
0.625, 0.75, 0.6, 0.66
```

In [136]:
def main_metrics(y_real, y_pred) -> (float, float, float, float):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass

# SLIDE (1) Основы метрик регрессии

Решаем задачу регрессии. На вход подаются 2 массива $y_{real}$ - реальные значения функции и $y_{pred}$ - предсказанные значения функции. Вам необходимо посчитать, не используя стандартные функции, метрики: 
* $R^2score$
* $MAE$ - `mean_absolute_error`
* $MSE$ - `mean_squared_error`
* $MSLE$ - `mean_squared_log_error`

Возвращать числа нужно именно в данном порядке.

Формулы для метрик - ищите в интернете, это часть задания. Можете сверяться с реальными метриками в `sklearn.metrics`.

Все числа в тестах больше 0, поэтому $MSLE$ будет считаться корректно
### Sample 1
#### Input:
```python
y_real = np.array([1, 2, 3, 4, 6])
y_pred = np.array([1, 3, 2, 4, 5])
```
#### Output:
```python
0.797297, 0.6, 0.6, 0.037856
```

In [136]:
def reg_metrics(y_real, y_pred) -> (float, float, float, float):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass

# SLIDE (1) LogLoss

Реализуйте свой LogLoss метрику.

В результат $y_{real}$ - передаются значения бинарных классов. В $y_{prob}$ - передаются вероятности $P(y_{pred}=1)$. Чтобы обработать краевые случаи в $y_{prob}$: 
* $0$ нужно заменить на `eps`
* $1$ нужно заменить на ($1$ - `eps`).
### Sample 1
#### Input:
```python
y_real = np.array([  1,   1,   0,   0,   1,   0,   1,   0])
y_prob = np.array([  1, 0.8, 0.2, 0.2, 0.4, 0.4, 0.6,   0])
```
#### Output:
``` python
    0.325921
```

In [107]:
def logloss(y_real, y_pred, eps=1e-15):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass


# SLIDE (2) Нахождение Roc-curve

Вам на вход даны $y_{real}$ и массив вероятностей $P(y_{pred}=1)$ необходимо реализовать функцию `roc-curve`, которая вернет 2 массива различных значений fpr и tpr, для дальнейшего построения Roc кривой.

Можно считать, что все вероятности ограничены $decimal=2$ (у каждого числа не более 2-х знаков после запятой)

### Sample
#### Input:
```python
y_real = np.array([  1,   1,   0,   0,   0,   1,   0,   1,   0])
y_prob = np.array([0.8, 0.8, 0.2, 0.2, 0.6, 0.4, 0.6, 0.6, 0.4])
```
#### Output:
```python
array([0.,  0.,  0.4, 0.6, 1. ]), #fpr
array([0., 0.5, 0.75,  1., 1. ])  #tpr
```

### Sample 2
#### Input:
```python
y_real = np.array([  1,   1,   0,   0,   1,   0,   1,   0])
y_prob = np.array([0.8, 0.8, 0.2, 0.2, 0.4, 0.4, 0.6, 0.6])
```
#### Output:
```python
array([0.,  0., 0.25, 0.5, 1. ]), #fpr
array([0., 0.5, 0.75,  1., 1. ])  #tpr

или 

array([0.,  0., 0.5, 1. ]), #fpr
array([0., 0.5,  1., 1. ])  #tpr
```

Обратите внимание на 2 пример: roc кривая, которая задается ими - одинаковая. Точка, которая уходит, находится на прямой между двумя соседними, в целом такие точки можно убирать, но будут приниматься оба варианта. Функция `sklearn.metrics.roc_curve` возвращает второй вариант.

In [135]:
def roc_curve(y_real, y_prob) -> (np.array, np.array):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass

# SLIDE (1) Кросс-валидация

На вход падаются [данные](https://yadi.sk/d/6pUM_Ko-RtqiZg) и $k$ - число фолдов в кросс-валидации. Верните значения кросс-валидации по $k$ фолдам алгоритма `LogisticRegression` с метрикой `neg_log_loss`. 

В итоге должны получиться значения не ниже $-1$.

### Sample
#### Input:
```python
X = pd.read_csv('resources/train.csv').drop(columns=['y']).values
Y = pd.read_csv('resources/train.csv')['y']
k = 3
```
#### Output:
```python
array([-0.45456358, -0.41684932, -0.49260998])
```

In [297]:
def crossvalidate(X, y, k):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass

# SLIDE (1) GridSearch

C помощью [GridSearch](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) найдите лучшие коэффициенты гиперпараметров `max_depth` и `min_samples_leaf` для классификатора [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) и верните обученный grid_search. 

* Пределы `max_depth` $(1, 10)$ 
* Пределы `min_samples_leaf` $(1, 10)$  
* Входные данные по [ссылке](https://yadi.sk/d/6pUM_Ko-RtqiZg)
* scoring - `precision`
* cv - $5$
* Другие параметры в `DecisionTreeClassifier` не указывать.

Не нужно Shuffl-ить данные, это может повлиять на ответ и в итоге задача не зачтется.

In [455]:
import numpy as np
from sklearn.model_selection import GridSearchCV

def fit_gs(X: np.ndarray, y: np.ndarray) ->  GridSearchCV:
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass

# SLIDE (1) RandomSearch

C помощью [RandomSearch](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html) найдите лучшие коэффициенты гиперпараметров `max_depth` и `min_samples_leaf` для классификатора [DecisionTreeClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html). 

Обучите $2$ `DTC`. Один с количеством итераций - $10$, другой с количеством итераций $50$. Верните обе обученные модели в соответствующем порядке.

* Пределы `max_depth` $(1, 10)$ 
* Пределы `min_samples_leaf` $(1, 10)$  
* Входные данные по [ссылке](https://yadi.sk/d/6pUM_Ko-RtqiZg)
* scoring - `precision`
* cv - $5$
* Другие параметры в `DecisionTreeClassifier` не указывать.

Не нужно Shuffl-ить данные, это может повлиять на ответ и в итоге задача не зачтется.

In [455]:
import numpy as np
from sklearn.model_selection import  RandomizedSearchCV

def fit_gs(X: np.ndarray, y: np.ndarray) -> (RandomizedSearchCV, RandomizedSearchCV):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass

# SLIDE (2) Моя Кросс-валидация

Вам необходимо реальзовать собственную функцию кросс-валидации. 

Напоминание, кросс-валидация: 
1. Разбивает, предварительно перемешав, данные на $k$ (заданное) `фолдов` данных (если нацело данные не делятся - хвост отбрасываем).
2. Берет один из фолдов за тестовую выборку, а все остальное за тренировачную.
3. Обучает эстиматор на тренировачных данныx 
4. Cчитает `score` обученной модели.
5. 2-4 шаги повторяются для всех $k$ фолдов 

Она должна принимать на вход: 
* `estimator`, который мы хотим обучить на разных фолдах данных
* $X, y$ - данные 
* `cv` ($k$) - объект разбиения `KFold` или количество фолдов, на которые мы бьем данные (по умолчанию 3)
* `scoring` - функция метрики, по которой оцениваем полученные результаты (замечание: в реальной `cross_val_score` здесь будет стоять объект `scorer`, у нас же будет стоять функция, например `metrics.accuracy_score`)

На выходе мы получаем массив длины $k$ из score значений.

Подсказка: используйте `model_selection.KFold` для разбиения выборки.

Подсказка: не нужно shuffl-ить данные при создании `KFold` из `cv`! 

### Sample
#### Input:
```python
estimator = LinearRegression()
X = np.array([[1],[2],[3],[4],[5]])
y = np.array([1, 2, 4, 4, 6])
cv = 2
scoring = sklearn.metrics.r2_score
```
#### Output:
```python
array([-2.64285714 -0.23611111])
```

In [60]:
from sklearn.metrics import accuracy_score, r2_score

def my_cross_val_score(estimator, X, y, cv=3, scoring=accuracy_score, random_state=42):
    ### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ
    pass